#ifndef CONFIG_H
#define CONFIG_H

#include <stdint.h>
#include <stdbool.h>

// --- AUDIO CONFIGURATION (MUST MATCH TRAINING SCRIPT) ---
#define SAMPLE_RATE 16000
#define WINDOW_DURATION_MS 1500  // 1.5 seconds
#define HOP_DURATION_MS 500      // 0.5 seconds
#define N_MELS 64
#define N_FFT 1024
#define MAX_SPECTROGRAM_WIDTH 48

// Derived constants
#define WINDOW_SAMPLES (SAMPLE_RATE * WINDOW_DURATION_MS / 1000)  // 24000 samples
#define HOP_SAMPLES (SAMPLE_RATE * HOP_DURATION_MS / 1000)        // 8000 samples
#define FFT_SIZE N_FFT
#define MEL_FILTER_BANK_SIZE N_MELS

// --- CONFIDENCE ACCUMULATOR PARAMETERS ---
#define PREDICTION_THRESHOLD 0.80f
#define CONFIDENCE_THRESHOLD 0.95f
#define INCREMENT_AMOUNT 0.15f
#define DECAY_RATE 0.05f
#define COOLDOWN_SECONDS 10

// --- HARDWARE CONFIGURATION ---
// PDM Microphone pins (ESP32-S3)
#define PDM_CLK_GPIO 42
#define PDM_DATA_GPIO 41

// LED indicator pin
#define LED_GPIO 2

// --- MEMORY CONFIGURATION ---
#define AUDIO_BUFFER_SIZE (WINDOW_SAMPLES * 2)  // Double buffer for safety
#define SPECTROGRAM_BUFFER_SIZE (N_MELS * MAX_SPECTROGRAM_WIDTH)

// --- MODEL CONFIGURATION ---
#define MODEL_INPUT_SIZE (N_MELS * MAX_SPECTROGRAM_WIDTH)
#define MODEL_OUTPUT_SIZE 2  // ["other_sounds", "lg_melody"]
#define LG_MELODY_CLASS_INDEX 1

// --- DEBUG CONFIGURATION ---
#define DEBUG_LEVEL 2 // 0=none, 1=basic, 2=verbose, 3=spectrogram_dump

// --- TASK PRIORITIES ---
#define AUDIO_CAPTURE_TASK_PRIORITY 5
#define PROCESSING_TASK_PRIORITY 4
#define MAIN_TASK_PRIORITY 3

// --- TASK STACK SIZES ---
#define AUDIO_CAPTURE_TASK_STACK_SIZE 8192
#define PROCESSING_TASK_STACK_SIZE 16384
#define MAIN_TASK_STACK_SIZE 4096

// --- QUEUE SIZES ---
#define AUDIO_QUEUE_SIZE 4

// --- MATHEMATICAL CONSTANTS ---
#define PI 3.14159265358979323846f
#define LOG10_E 0.43429448190325182765f
#define MEL_SCALE_FACTOR 2595.0f
#define MEL_BREAK_FREQUENCY 700.0f

// --- POWER TO DB CONVERSION ---
#define DB_MIN -80.0f
#define DB_REF_POWER 1.0f

#endif // CONFIG_H
